[package]
name = "ak_macros"
version = "1.0.0"
edition = "2021"
readme = "README.md"
authors = ["Hamdy-Mohamedak <mohameddhamdy407@gmail.com>"]
description = "A script-like macro toolkit for clean, expressive Rust automation"
license = "MIT"
repository = "https://github.com/hamdymohamedak/AK-macro/"
homepage = "https://ak-macros.vercel.app"
keywords = [
    "ak-macros",
    "macro",
    "cli",
    "automation",
    "productivity",
]
categories = ["development-tools", "command-line-utilities"]
rust-version = "1.74"

[features]
default = ["std"]
std = []
advanced = []

[lints.rust]
rust_2018_idioms = "deny"
unused_lifetimes = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "deny"

[dependencies]
